name: AKS
on:
  push:
    branches:
      - dev
    path:
      - "aks/**"

jobs:
  deploy-aks:
    runs-on: ubuntu-20.04
    steps:

      - name: Recuperation du repo
        uses: actions/checkout@v2 

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1

      - name: Kustomize edit
        run: |
          cd ./Kubernetes/
          echo $IMAGE
          echo ${GITHUB_SHA::8}
          kustomize edit set image aspnet5webapp:latest=$IMAGE/aspnet5webapp:${GITHUB_SHA::8}
        env:
          IMAGE: ub5xcwoyadb26acr.azurecr.io

      - name: check
        run: ls -R ./Kubernetes/