name: AKS
on:
  push:
    branches:
      - dev
    path:
      - "aks/**"

jobs:
  deploy-aks:
    runs-on: ubuntu-20.04
    steps:
    

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1